// Downloads the Ludos webfonts from Google Fonts and self-hosts them.
//
//   node scripts/fetch-fonts.mjs
//
// Writes woff2 files to public/fonts/ and generates src/styles/fonts.css.
// Self-hosting keeps the app independent of fonts.googleapis.com: no
// third-party request at runtime, no flash of fallback text, and the design's
// exact typefaces render even on a locked-down network.

import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const fontDir = resolve(root, 'public/fonts');
const cssOut = resolve(root, 'src/styles/fonts.css');

// A modern UA is required, otherwise Google serves legacy ttf instead of woff2.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// Only Latin subsets — the app has no Cyrillic/Greek/Vietnamese copy.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  {
    name: 'Familjen Grotesk',
    // UI sans. 700 is used by the welcome headline and review names.
    query: 'Familjen+Grotesk:wght@400;500;600;700',
  },
  {
    name: 'Newsreader',
    // Editorial serif. Italic 400 carries the review quotes and archetype names.
    query: 'Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,400',
  },
];

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
  return res.text();
}

/** Splits the Google CSS into per-subset @font-face blocks. */
function parseBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css))) blocks.push({ subset: m[1], rule: m[2] });
  return blocks;
}

const field = (rule, name) => rule.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim();
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-');

await mkdir(fontDir, { recursive: true });

// These are variable fonts: every weight in a family resolves to the same
// file, so Google emits one near-identical rule per weight. Group them and
// emit a single rule carrying a weight *range* instead.
const groups = new Map();
const downloads = new Map();

for (const family of FAMILIES) {
  const css = await fetchText(
    `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`,
  );

  for (const { subset, rule } of parseBlocks(css)) {
    if (!KEEP_SUBSETS.has(subset)) continue;

    const url = rule.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;

    const style = field(rule, 'font-style') ?? 'normal';
    const weight = Number(field(rule, 'font-weight') ?? 400);
    const range = field(rule, 'unicode-range') ?? '';

    const file = `${slug(family.name)}-${style}-${subset}.woff2`;
    downloads.set(file, url);

    const key = `${family.name}|${style}|${subset}`;
    const group = groups.get(key);
    if (group) {
      group.min = Math.min(group.min, weight);
      group.max = Math.max(group.max, weight);
    } else {
      groups.set(key, { family: family.name, style, subset, file, range, min: weight, max: weight });
    }
  }
}

const rules = [...groups.values()].map(
  (g) => `/* ${g.family} — ${g.style}, ${g.subset} */
@font-face {
  font-family: '${g.family}';
  font-style: ${g.style};
  font-weight: ${g.min === g.max ? g.min : `${g.min} ${g.max}`};
  font-display: swap;
  src: url(/fonts/${g.file}) format('woff2');
  unicode-range: ${g.range};
}`,
);

let bytes = 0;
for (const [file, url] of downloads) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} downloading ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  bytes += buf.length;
  await writeFile(resolve(fontDir, file), buf);
}

await writeFile(
  cssOut,
  `/* Generated by scripts/fetch-fonts.mjs — do not hand-edit.
   Self-hosted so the app never depends on fonts.googleapis.com at runtime.
   Regenerate with: npm run fonts */

${rules.join('\n\n')}
`,
);

console.log(
  `${downloads.size} font files (${(bytes / 1024).toFixed(0)} KB) → public/fonts/\n` +
    `${rules.length} @font-face rules → src/styles/fonts.css`,
);
